name: archanai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  convert: ^3.1.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - asserts/images/
flutter-json:
    enabled: true
